# 本地开发环境配置
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "@Value123456"
    driver-class-name: org.postgresql.Driver
  ai:
    # 向量数据库配置
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536  # text-embedding-v2 使用 1536 维度
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
